/**
 * The AI compensation release PayUp ships. Generated by uptop-crons
 * scripts/frontier_public_export.py into public/data/ai-comp/; the manifest is imported at
 * build time (fixed path), observations are fetched at runtime and verified against the
 * manifest's SHA-256 before any statistic is shown. Nothing here is hand-edited.
 */
import manifestJson from "../../public/data/ai-comp/latest-manifest.json";

export interface QualityCheck {
  name: string;
  status: "pass" | "warn" | "fail";
  detail: string;
}

export interface ReleaseManifest {
  schema_version: string;
  release_id: string;
  generated_at: string;
  generator: { script: string; rules_version: string; cohort_config: { schema_version: string | null; reviewed_at: string | null; sha256: string } };
  source: {
    kind: string;
    store_sha256: string;
    batch: { batch_id: string; started_at: string; completed_at: string | null; status: string; expected_boards: number; success_boards: number; failed_boards: number };
    boards_configured: number;
    companies_with_open_roles_in_store: number;
  };
  observation_window: { posted_at_min: string | null; posted_at_max: string | null; verified_open_on: string | null; note: string };
  counts: {
    store_open_roles: number;
    market_companies: number;
    observations: number;
    with_posted_range: number;
    usd_annual_eligible: number;
    duplicates_collapsed: number;
    excluded_rows: Record<string, number>;
    observation_flags: Record<string, number>;
  };
  markets: Record<string, { label: string; definition: string; cohorts: string[]; companies: number; open_postings: number; usd_annual_eligible: number }>;
  cohorts: Record<string, { label: string; sector: string; definition: string; companies_in_release: number }>;
  role_families: Record<string, string>;
  levels: Record<string, string>;
  display_rules: { min_postings: number; min_employers: number };
  definitions: Record<string, string>;
  privacy: { private_evidence_included: boolean; statement: string };
  quality_checks: QualityCheck[];
  files: Record<string, { sha256: string; bytes: number; rows?: number; format?: string; columns?: string[] }>;
}

export const MANIFEST = manifestJson as unknown as ReleaseManifest;
export const RELEASE_ID = MANIFEST.release_id;
export const OBSERVATIONS_URL = `/data/ai-comp/${RELEASE_ID}/observations.json`;

export interface Observation {
  id: string;
  company_id: string;
  company: string;
  cohort: string;
  markets: string[];
  title: string;
  role_family: string;
  role_family_confidence: string;
  level: string;
  level_confidence: string;
  employment_type: string;
  location_raw: string;
  country: string;
  metro: string;
  metros?: string[];
  work_arrangement: string;
  geo_confidence: string;
  evidence_kind: string;
  component: string;
  component_confidence: string;
  currency: string | null;
  pay_period: string;
  pay_period_confidence: string;
  amount_low: number | null;
  amount_high: number | null;
  range_swapped: boolean;
  source_text: string | null;
  source_url: string | null;
  observed_at: string | null;
  fetched_at: string | null;
  equity_offered: boolean | null;
  usd_annual_eligible: boolean;
  exclusion_reasons: string[];
  duplicate_count?: number;
}

export interface ColumnarPayload {
  schema_version: string;
  release_id: string;
  format: "columnar";
  columns: string[];
  rows: unknown[][];
}

export function hydrate(payload: ColumnarPayload): Observation[] {
  const { columns, rows } = payload;
  return rows.map((row) => {
    const o: Record<string, unknown> = {};
    columns.forEach((c, i) => {
      o[c] = row[i];
    });
    if (o.metros === null) delete o.metros;
    if (o.duplicate_count === null) delete o.duplicate_count;
    return o as unknown as Observation;
  });
}

export async function sha256Hex(bytes: ArrayBuffer): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

export type LoadState =
  | { status: "loading" }
  | { status: "ready"; observations: Observation[] }
  | { status: "error"; message: string };

/** Fetch + verify + hydrate. A checksum mismatch is an error state — statistics are withheld, not degraded. */
export async function loadObservations(fetcher: typeof fetch = fetch): Promise<Observation[]> {
  const res = await fetcher(OBSERVATIONS_URL, { cache: "force-cache" });
  if (!res.ok) throw new Error(`observations fetch failed: HTTP ${res.status}`);
  const buf = await res.arrayBuffer();
  const expected = MANIFEST.files["observations.json"]?.sha256;
  const actual = await sha256Hex(buf);
  if (!expected || actual !== expected) {
    throw new Error("Data integrity check failed: observations.json does not match the manifest checksum. Benchmarks withheld.");
  }
  const payload = JSON.parse(new TextDecoder().decode(buf)) as ColumnarPayload;
  if (payload.release_id !== RELEASE_ID) throw new Error("Release id mismatch between manifest and observations.");
  const rows = hydrate(payload);
  if (rows.length !== MANIFEST.files["observations.json"].rows) throw new Error("Observation row count does not match the manifest.");
  return rows;
}
